# fly.toml app configuration file generated for wellness-connect on 2025-10-07T00:59:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# REQUIRED SECRETS (set via `fly secrets set`):
# - RAILS_MASTER_KEY: Rails credentials encryption key (from config/master.key)
# - DATABASE_URL: PostgreSQL connection string (automatically set by Fly.io)
# - AWS_ACCESS_KEY_ID: Tigris storage access key
# - AWS_SECRET_ACCESS_KEY: Tigris storage secret key
# - AWS_ENDPOINT_URL_S3: Tigris storage endpoint (https://fly.storage.tigris.dev)
# - BUCKET_NAME: Tigris storage bucket name
#
# See docs/FLYIO_TIGRIS_SETUP.md for detailed setup instructions
# See docs/DEPLOYMENT_CHECKLIST.md for deployment checklist

app = 'wellness-connect'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'
  solidq = 'bundle exec rake solid_queue:start'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
